doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded

        'App\Nottes\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Nottes/Infrastructure/Persistence/Doctrine/Migrations'

    enable_profiler: '%kernel.debug%'
