# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
  serializer:
    serialize_null: true
  disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
  param_fetcher_listener: true
  body_listener: true
  format_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json : true
    force_redirects:
      html: true
    failed_validation: HTTP_BAD_REQUEST
    default_engine: twig
    serialize_null: true
  routing_loader:
    default_format: json