nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Nottes
            description: Nottes backend
            version: 1.0.0
    areas: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc