<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '6055a88d19788215ac9e2ff6299250ab',
  'DATABASE_URL' => 'mysql://root:password@172.28.1.2:3306/nottes_app?serverVersion=8&charset=utf8mb4',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
