App\Nottes\Domain\Folder\Folder:
  shortName: 'Folder'
  description: 'Resource'
  iri: 'https://schema.org/Folder'
  attributes: []
  collectionOperations:

    create_folder:
      method: 'POST'
      path: '/folder'
      schemes: [ 'https', 'http' ]
      controller: Nottes\Apps\Api\Controller\Folder\CreateFolderController
      defaults:
        _api_receive: false
      openapi_context:
        summary: 'Create Folder'
        consumes:
          - application/json

        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: { type: string }
                  description: { type: string }
                  parent: {type: string }

        responses:
          200:
            description: 'Survey Fulfillment'
          400:
            description: 'Incorrect Parameters'

#    get_folder_list:
#      method: 'GET'
#      path: '/folders'
#      schemes: [ 'https', 'http' ]
#      controller: Nottes\Apps\Api\Controller\Survey\GetSurveyListController
#      defaults:
#        _api_receive: false
#      swagger_context:
#        summary: 'Get Surveys list'
#        description: ''
#        parameters: [ ]
#        responses:
#          200:
#            description: 'Surveys list'

  itemOperations: []

#    get_survey_detail:
#      method: 'GET'
#      path: '/survey/{id}'
#      schemes: [ 'https', 'http' ]
#      controller: Nottes\Apps\Api\Controller\Survey\GetSurveyDetailByIdController
#      defaults:
#        _api_receive: false
#      swagger_context:
#        summary: 'Get Survey detail by id'
#        description: ''
#        parameters: []
#        responses:
#          200:
#            description: 'Survey detail'
#          400:
#            description: 'Incorrect Parameters'
