App\Nottes\Domain\Folder\Folder:
  shortName: 'Folder'
  description: 'Resource'
  iri: 'https://schema.org/Folder'
  attributes: []
  collectionOperations:

    create_folder:
      method: 'POST'
      path: '/folder'
      schemes: [ 'https', 'http' ]
      controller: Nottes\Apps\Api\Controller\Folder\FolderPostController
      defaults:
        _api_receive: false
      openapi_context:
        summary: 'Create Folder'
        consumes:
          - application/json

        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: { type: string }
                  description: { type: string }
                  parent: {type: string }

        responses:
          200:
            description: 'Survey Fulfillment'
          400:
            description: 'Incorrect Parameters'

    get_folder_collection_search:
      method: 'GET'
      path: '/folders'
      schemes: [ 'https', 'http' ]
      controller: Nottes\Apps\Api\Controller\Folder\FolderGetCollectionController
      defaults:
        _api_receive: false
      openapi_context:
        summary: 'Get Folder content collection'
        description: ''
        parameters:
          - in: query
            name: filters
            required: false
            schema:
              type: array
              items:
                type: object
                properties:
                  field: { type: string }
                  operator: { type: string }
                  value: { type: string }
          - in: query
            name: order_by
            required: false
            schema:
              type: string
        responses:
          200:
            description: 'Folder content'

  itemOperations:

    get_folder_detail:
      method: 'GET'
      path: '/folder/{id}'
      schemes: [ 'https', 'http' ]
      controller: Nottes\Apps\Api\Controller\Folder\FolderGetController
      defaults:
        _api_receive: false
      swagger_context:
        summary: 'Get folder content by id'
        description: ''
        parameters: []
        responses:
          200:
            description: 'Folder detail'
          400:
            description: 'Incorrect Parameters'
