App\Entity\Document:
    exclusion_policy: ALL
    properties:
        
        id:
          expose: true
          groups: 
            - notteList

        name:
          expose: true
          groups: 
            - notteList

        path:
          expose: true
          groups: 
            - notteList