App\Entity\Document:
    exclusion_policy: ALL
    properties:
        
        id:
          expose: true

        name:
          expose: true

        path:
          expose: true

        mimetype:
          expose: true

        creatorUser:
          expose: true
