version: "2"
services:

    webserver:
      image: nginx:alpine
      container_name: nottes-webserver
      working_dir: /application
      volumes:
          - ../../:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8083:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: nottes-php-fpm
      working_dir: /application
      volumes:
        - ../../:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      ports:
        - "9003:9000"

