# home
index:
    path: /
    controller: App\Controller\Home\HomeController::index

# users
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
   path: /api/login_check

# nottes

# swagger
app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
