# config/doctrine/Document.orm.yml
App\Entity\Document:
    type: entity
    table: documents
    repositoryClass: App\Repository\DocumentRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        
        name:
            type: string
            length: 255
        
        path:
            type: string
            length: 255
        
        size:
            type: decimal
            length: 50

        mimetype:
            type: string
            length: 255

        createdAt:
            type: datetime

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue ]
