# config/doctrine/Notte.orm.yml
App\Entity\Notte:
    type: entity
    table: nottes
    repositoryClass: App\Repository\NotteRepository

    manyToOne:

        creatorUser:
          targetEntity: App\Entity\User
          joinColumn:
            name: creator_user_id
            referencedColumnName: id

        document:
          targetEntity: App\Entity\Document
          joinColumn:
            name: document_id
            referencedColumnName: id
            onDelete: CASCADE
            nullable: true

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 5
        content:
            type: text
            nullable: true
        tags:
            type: string
            length: 255
            nullable: true
        isEncrypted:
            type: boolean
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue ]
        preUpdate: [ setUpdatedValue ]
