# config/doctrine/Notte.orm.yml
App\Entity\Notte:
    type: entity
    table: nottes

    manyToOne:

        creatorUser:
          targetEntity: App\Entity\User
          joinColumn:
            name: creator_user_id
            referencedColumnName: id

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        content:
            type: text
        tags:
            type: string
            length: 255
            nullable: true
        isEncrypted:
            type: boolean
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        
