# config/doctrine/User.orm.yml
App\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:

        language:
            type: string
            column: language
            options:
                default: 'en'
