# config/doctrine/UserAccess.orm.yml
App\Entity\UserAccess:
    type:  entity
    table: user_access

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:

        email:
            type: string
            column: email

        ip:
            type: string
            column: ip

        userAgent:
            type: text
            column: user_agent
            nullable: true

        successfulLogin:
            type: boolean
            column: successful_login

        time:
            type: datetime
            column: time

